### PR TITLE
Use ConcurrentQueue rather than Pool scan

### PR DESCRIPTION
**Pull request by benaadams**
@rynowak worth doing? Not sure how large the general pool sizes are.

Could also do a circular buffer instead...

### CODE REVIEW

**Comment by rynowak** [comment]
> worth doing?

Not without data

**Comment by Eilon** [comment]
Sorry for being late to the party. Are we interested in getting data on this? Has this been identified as a hotspot before?

**Comment by rynowak** [comment]
It would be worth doing some profiling here of a few usages of this, I think link generation in routing is the most interesting candidate.

**Comment by Eilon** [comment]
Closing this out for now because we don't have specific data on this scenario.

**Pull request closed without merging**
