### PR TITLE
Null params in matcher

### PR DESCRIPTION
**Pull request by BrennanConroy**
@Tratcher 
https://github.com/aspnet/HttpAbstractions/issues/331

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Ping @Tratcher

**Comment by Tratcher** [comment]
Write a test here or in HttpAbstractions.

**Comment by davidfowl** [comment]
Write a test here.

**Comment by BrennanConroy** [comment]
Added a test

**Comment by Tratcher** [comment]
:shipit:

**Comment by davidfowl** [comment]
This code is used by many other places. Is this behavior the right thing in all cases (I think not). Can you make a list of the callers and see if there are unintended side effects?

**Comment by BrennanConroy** [comment]
Most uses of the ActivatorUtilities function is using the overload that doesn't take a param [] of args so they are unaffected by this change.

SignalR-Server uses it a couple times mostly in tests, Mvc uses it once and passes a string
So nothing looks like it will break

Also, DependencyInjection has it's own implementation of this class (looks like just copy pasta from some time ago)

**Comment by BrennanConroy** [comment]
Ping @davidfowl

**Comment by davidfowl** [comment]
we shouldn't allow nulls by default. It should be indicated with a default value like:

```C#
public class Foo
{
   public Foo(Something x = null, SomethingNotNull y)
   {
   }
}
```

/cc @pranavkm Don't we support something like this?

**Comment by pranavkm** [comment]
Yes, default values should work. However @davidfowl, your example wouldn't actually compile. `SomethingNotNull y` would also require a default parameter.

**Comment by Eilon** [comment]
Any update on this PR?

I'm not entirely sure I like this behavior. The `null` support just seems wrong.

**Pull request closed without merging**
