### PR TITLE
[NoMerge] StringValues convert to Empty Array

### PR DESCRIPTION
**Pull request by benaadams**
/cc @halter73 @Tratcher @dougbu

### CODE REVIEW

**Comment by Tratcher** [comment]
Heads up, the original change was reverted. We'll reintroduce it more cautiously by doing full universe builds before merging.

**Comment by Tratcher** [comment]
@benaadams this change matches our best theory on how to mitigate the risks of the other changes. Can you cherry pick your prior commits back into this PR? 

Ever run a full universe build?

**Comment by benaadams** [comment]
Will have a browse at https://github.com/aspnet/Universe

**Comment by Tratcher** [comment]
The gist is that you make your changes in your branch and push them. Then you clone universe including submodules, update the Common submodule to point at your branch/commit, and then build the root universe.

**Comment by benaadams** [comment]
Know what I need installed for IISIntegration?
```
 >>> dotnet.exe msbuild @C:\GitHub\Universe\modules\IISIntegration\artifacts\logs\msbuild.rsp @C:\GitHub\Universe\modules\IISIntegration\artifacts\logs\msbuild.logger.rsp
  IISIntegration        | Build started.
  IISIntegration        | C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-15745\modules\KoreBuild.Tasks\module.targets(140,5): error :
 Could not find an installation of Visual Studio that satisifies the specified requirements in 
C:\GitHub\Universe\modules\IISIntegration\/korebuild.json. 
See https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community for more details on any missing components.
  IISIntegration        |
  IISIntegration        | Build FAILED.
  IISIntegration        |
  IISIntegration        | C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-15745\modules\KoreBuild.Tasks\module.targets(140,5): error : Could not find an installation of Visual Studio that satisifies the specified requirements in C:\GitHub\Universe\modules\IISIntegration\/korebuild.json. See https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community for more details on any missing components.
  IISIntegration        |     0 Warning(s)
  IISIntegration        |     1 Error(s)
  IISIntegration        |
  IISIntegration        | Time Elapsed 00:00:00.30
  dotnet.exe failed with exit code: 1
  At C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-15745\scripts\common.psm1:11 char:9
  +         throw "$cmdName failed with exit code: $exitCode"
  +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit code: 1:String) [], RuntimeException
      + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1
```

**Comment by benaadams** [comment]
Ah, ok
```
"requiredWorkloads": [
  "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
  "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81",
  "Microsoft.VisualStudio.Component.VC.ATL",
  "Microsoft.VisualStudio.Component.Windows10SDK.15063.Desktop"
]

```

**Comment by benaadams** [comment]
Is there a way to get Universe builds to log? When it goes wrong I just get a thousand lines of red, but can't scroll back to see what the initial error was as it fills the console buffer pretty fast

**Comment by Tratcher** [comment]
Pipe to file?

**Comment by halter73** [comment]
Use `tee` so you can still see the output while piping to a file.

**Comment by benaadams** [comment]
Piror to change, Think this is just it being grumpy
```
Build FAILED.

warning : Skipping template tests because InstallSharedRuntimeFromPreviousBuild != 'true'. [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error : Tests failed for the following repos: [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - AADIntegration [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - Identity [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - AzureIntegration [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - Scaffolding [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - MvcPrecompilation [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - MusicStore [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - Razor [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
```

Need to find what fails with change

**Comment by benaadams** [comment]
A lot of test errors seem to be `\n\r` vs `\r`
```
Build FAILED.

warning : Skipping template tests because InstallSharedRuntimeFromPreviousBuild != 'true'. [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error : Tests failed for the following repos: [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - Mvc [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - AADIntegration [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - AzureIntegration [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - Identity [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - Scaffolding [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - MvcPrecompilation [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - MusicStore [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - Razor [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
 error :  - HttpSysServer [C:\Users\thund\.dotnet\buildtools\korebuild\2.1.0-preview3-17001\KoreBuild.proj]
```
`Mvc` and `HttpSysServer` are new; will prepare fixes

**Comment by benaadams** [comment]
@Tratcher `HttpSysServer` is inconsistent between known and unknown headers and empty/nulls; this change will bring them closer, but not all the way..?
```csharp
public static TheoryData<string, StringValues, StringValues> NullHeaderData
{
    get
    {
        var dataset = new TheoryData<string, StringValues, StringValues>();

        // Unknown headers
        dataset.Add("NullString", (string)null, (string)null);
        dataset.Add("EmptyString", "", "");
        dataset.Add("NullStringArray", new string[] { null }, "");
        dataset.Add("EmptyStringArray", new string[] { "" }, "");
        dataset.Add("MixedStringArray", new string[] { null, "" }, new string[] { "", "" });
        // Known headers
        dataset.Add("Location", (string)null, (string)null);
        dataset.Add("Location", "", (string)null);
        dataset.Add("Location", new string[] { null }, (string)null);
        dataset.Add("Location", new string[] { "" }, (string)null);
        dataset.Add("Location", new string[] { "a" }, "a");
        dataset.Add("Location", new string[] { null, "" }, (string)null);
        dataset.Add("Location", new string[] { null, "", "a", "b" }, new string[] { "a", "b" });

        return dataset;
    }
}
```

**Comment by benaadams** [comment]
Actually with https://github.com/aspnet/HttpAbstractions/pull/1010 it might bring them completely inline

**Comment by benaadams** [comment]
Except dropping nulls from arrays that contain values also; which it does for known headers (backed that change out in the previous PR)

**Pull request closed without merging**
