### PR TITLE
ClosedGenericMatcher reduced alloc

### PR DESCRIPTION
**Pull request by benaadams**
Is an ```internal static``` class that doesn't seem to be referenced except in tests so probably either dead code; or testing code - but for completeness....

### CODE REVIEW

**Comment by dougbu** [comment]
@benaadams this is a shared source project used in the MVC and Razor repos. Do you have any numbers demonstrating your changes improve performance in a real scenario using at least Razor?

**Comment by benaadams** [comment]
```Func<Type, bool> matchesInterface``` allocates a closure per call to capture ```Type interfaceType``` so moved that out into ```static Func<Type, Type, bool> MatchesInterface```

However ```queryType.GetTypeInfo().ImplementedInterfaces.FirstOrDefault``` only passes a single argument, hence the need for the closure; so changed the Linq to a ```foreach```.

Its not perfect as its still going to allocate on the ```ImplementedInterfaces``` ```IEnumerable``` for the ```foreach``` as it would have done for the Linq; but I had it hanging around - ok if you take it or leave it.

**Comment by dougbu** [comment]
@benaadams that's not enough for a change here. Does anything about the current implementation show up in a profile using Razor or MVC features that use this code?

**Comment by benaadams** [comment]
I'm guessing its a cached resolve that's once per setup rather than per page/request? So doubtful it would show up in a profile and would be an unneeded optimisation.

If its something that could be called per request though; I can dig a bit deeper...?

**Comment by benaadams** [comment]
Closing as not aware of it being in a hot path.

**Comment by benaadams** [comment]
Just when you think you are safe... someone necroposts!

**Comment by benaadams** [comment]
And we have a player...

generic-matcher

**Comment by benaadams** [comment]
No, nothing to see here - move along....

`.GetInterfaces()` should probably returning a cached `Type[]` though, but that is elsewhere

**Comment by rynowak** [comment]
@benaadams - we're going to fix this in MVC by not calling into it as often. When in doubt do less work.

**Comment by benaadams** [comment]
Can't cache it further down as array's contents could be altered; which would muck up reflection quite heavily :(

Could static dictionary it; but that would mean it would need to be cleared on any dynamic loading/recomplilation?

**Pull request closed without merging**
