### PR TITLE
Utilize some C# 7 magic

### PR DESCRIPTION
**Pull request by henkmollema**
Even nicer would be to use tuples here. However, that requires the `System.ValueTuple` package. Thoughts?

### CODE REVIEW

**Comment by Eilon** [comment]
This looks like some nice cleanup, thanks! I don't think changing to tuples adds much value here, so let's stick with what we've got here now.

@dougbu - can you do a quick review & merge?

**Comment by henkmollema** [comment]
Allright, I'll leave it like this. :smile:

**Comment by dougbu** [comment]
Thanks very much @henkmollema

**Comment by henkmollema** [comment]
You're welcome! :tada:

**Pull request merged**
