### PR TITLE
Check for abstract types in ActivatorUtilities

### PR DESCRIPTION
**Pull request by henkmollema**
The exception asks the user to make sure the type is concrete, however this is not being checked.

### CODE REVIEW

**Comment by Eilon** [comment]
@henkmollema - this seems like a good change -- can you add a test for it? I'd want to make sure we don't regress this scenario in the future.

@pakrym - can you take a look?

**Comment by henkmollema** [comment]
@Eilon I would like to, however there aren't any tests on `ActivatorUtilities` yet. Should I create a new test project for it?

**Comment by henkmollema** [comment]
Tests are a WIP. Not ready for merge yet.

**Comment by Eilon** [comment]
Ah, that's scary then 😄 Well, it'd still be good to have a new test for the new functionality! And it would be super great if you could make sure that the test *fails* when you *don't* have your change enabled.

**Comment by pakrym** [comment]
We have tests for ActivatorUtilities in DI https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Specification.Tests/ActivatorUtilitiesTests.cs . Strange layering is because we had two implementations before, we unified them since and DIActivatorUtilities calls into this implementation, so maybe it makes sense to move all tests here.

**Comment by natemcmaster** [comment]
You can also add tests to the Microsoft.Extensions.Internal.Test project. That's our "kitchen sink" test project for all those one-class .Sources packages.

**Comment by henkmollema** [comment]
Allright, I'll add them to `Microsoft.Extensions.Internal.Test`.

**Comment by henkmollema** [comment]
@Eilon @pakrym @natemcmaster I've added a test to `Microsoft.Extensions.Internal.Test`. However, I do think that we shouldn't have two test projects for `ActivatorUtilities`. Should we merge them together in some place?

**Comment by Eilon** [comment]
Yeah I think moving all the tests here is the right thing to do, but that should be as a separate PR. I'm fine if for this PR we just lay the groundwork here with the new test(s) we want to add, and as a separate change we can pull in the other tests from the DI repo.

**Comment by henkmollema** [comment]
Sounds good to me!

**Comment by pakrym** [comment]
@henkmollema Thank you!

**Comment by henkmollema** [comment]
You're welcome!

**Pull request merged**
