### PR TITLE
Replace PlatformAbstractions with RuntimeInformation

### PR DESCRIPTION
**Pull request by BrennanConroy**
Part of https://github.com/aspnet/PlatformAbstractions/issues/34

### CODE REVIEW

**Comment by BrennanConroy** [comment]
One reference to platformabstractions still exists in this repo https://github.com/aspnet/Common/blob/8bbb93b29129cb84ef6b6baf8aa5ada6b6eb4614/src/Microsoft.Extensions.DotnetToolDispatcher.Sources/DotnetToolDispatcher.cs

**Comment by pranavkm** [comment]
:shipit: once build passes.

**Comment by pranavkm** [comment]
@Eilon \ @davidfowl - we could move that package to Common if we'd like to keep `ApplicationEnvironment` around. It's a pretty simple utility type now and doesn't need it's own repo.

**Comment by Eilon** [comment]
@pranavkm sorry, move what package to Common?

**Comment by pranavkm** [comment]
`Microsoft.Extensions.PlatformAbstractions`

**Comment by Eilon** [comment]
Meh, we can move it at a later time, no?

**Pull request merged**
