### PR TITLE
[2.1]: Move Ms.Extensions.Buffer.Sources files into aspnet/KestrelHttpServer

### PR DESCRIPTION
**Pull request by natemcmaster**
These files are only used in aspnet/KestrelHttpServer. Since @halter73's change in https://github.com/aspnet/Common/pull/381 only touched the MemoryPoolBlock.Release.cs file, let's move these sources into aspnet/kestrel so we don't have to patch the the aspnet/Common repo.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
SignalR has a reference to the testing package https://github.com/aspnet/SignalR/blob/release/2.1/test/Microsoft.AspNetCore.Http.Connections.Tests/Microsoft.AspNetCore.Http.Connections.Tests.csproj#L22

Not sure if it's just an old reference that can be cleaned up, or if we actually use something from there.

**Comment by BrennanConroy** [comment]
`ReadOnlySequenceFactory` is used https://github.com/aspnet/SignalR/blob/release/2.1/test/Microsoft.AspNetCore.Http.Connections.Tests/ServerSentEventsMessageFormatterTests.cs#L32

**Comment by natemcmaster** [comment]
Yeah, i'm working on a PR to signalR too. It only uses a really small portion of the class, so I'm not sure we gain much value from a .Sources package (which adds to the burden of servicing repo-to-repo changes).

**Comment by davidfowl** [comment]
Hmm can we talk about this before merging?

**Comment by natemcmaster** [comment]
What’s the concern?

**Comment by davidfowl** [comment]
Is this only for the patch? The concern is less code sharing. If it’s only for the patch branch I’m less concerned but we shouldn’t be doing this in general.

**Comment by natemcmaster** [comment]
No, I want this in 2.2 as well. There are two options here that I'm okay with.

1. https://github.com/aspnet/SignalR/pull/2622 - this duplicates about 100 lines of code that also lives in Kestrel. IMO this is minor amount of duplication and is super low impact.
2. We make aspnet/KestrelHttpServer produce the Microsoft.Extensions.Buffers.Testing.Sources package so SignalR doesn't have any duplication at all. Cons: sources packages are not easy to work with if you do end up needing to make changes.

**Comment by davidfowl** [comment]
Is rather have no duplication. I don’t quite understand the burden of using shared sources here.

**Comment by natemcmaster** [comment]
the burden is when you want to make a change to source from .Sources packages from another repo. Cross-repo work with sources packages is painful

**Comment by pakrym** [comment]
Keeping track of all the places code was copied to is as painful if not more.

**Comment by natemcmaster** [comment]
Ok, I update the kestrel PR so the Testing.Buffers.Sources thing is still a source package. There is no duplication between Kestrel and SignalR now. So this PR is just moving code closer to where it's actually used, which is primarily in Kestrel.

**Comment by natemcmaster** [comment]
:bell: you guys okay with this? We need to get this in today.

**Pull request merged**
