### PR TITLE
Add a convenience API for using timer in the right way

### PR DESCRIPTION
**Pull request by rynowak**
/cc @davidfowl @benaadams

### CODE REVIEW

**Comment by JamesNK** [comment]
Is this something that could be checked for with code analysis? (note: not in this PR)

**Comment by rynowak** [comment]
everything can be checked with code analysis if you're determined enough

**Comment by rynowak** [comment]
@benaadams - where did the fixes for this go in? Razor, HttpClientFactory, FileProviders, ??? others ???

**Comment by benaadams** [comment]
https://github.com/aspnet/Razor/pull/2565, https://github.com/aspnet/SignalR/pull/2904, https://github.com/aspnet/HttpClientFactory/pull/172


FileProviders was fixed by https://github.com/aspnet/Common/pull/392 which is similar, but different

**Pull request merged**
