### PR TITLE
Reacting to changes to MemoryManager (use CreateMemory)

### PR DESCRIPTION
**Pull request by ahsonkhan**
Part of https://github.com/dotnet/corefx/issues/28751

Depends on new corefx packages with this change: https://github.com/dotnet/corefx/pull/28981

cc @davidfowl, @pakrym, @KrzysztofCwalina, @GrabYourPitchforks, @benaadams

### CODE REVIEW

**Comment by benaadams** [comment]
How did the CI pass?

**Comment by ahsonkhan** [comment]
> How did the CI pass?

Lol. That is what I am wondering. Locally, it fails. Maybe it is only building release.

> D:\GitHub\Fork\Common\shared\Microsoft.Extensions.Buffers.Sources\MemoryPoolBlock.Debug.cs(51,24): error CS0103: The name 'CreateMemory' does not exist in the current context [D:\GitHub\Fork\Common\test\Microsoft.Extensions.Internal.Test\Microsoft.Extensions.Internal.Test.csproj]

**Comment by pakrym** [comment]
CI only builds release.

**Comment by ahsonkhan** [comment]
The latest versions have the change needed to make this PR pass (even for debug):
[2.1.0-preview3-26413-01](https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App/2.1.0-preview3-26413-01)
[4.5.0-preview3-26413-02](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory/4.5.0-preview3-26413-02)

Can we update Universe?

**Comment by pakrym** [comment]
Nope, our CI still on fire. But I would still try to get it in today.

**Comment by ahsonkhan** [comment]
> Nope, our CI still on fire. But I would still try to get it in today.

Related to forking master - Aspnet consumption shouldn't block us right?
cc @joshfree, @weshaggard

**Comment by pakrym** [comment]
It would break Prodcon as soon as we branch to preview/2.1 again.

**Pull request merged**
