### PR TITLE
Update common nuget package verifier

### PR DESCRIPTION
**Pull request by HaoK**
@smitpatel @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
@muratg @pranavkm says this may no longer be needed

**Comment by Tratcher** [comment]
https://github.com/aspnet/Logging/pull/494

**Comment by pranavkm** [comment]
We could add it for now. @ajaybhargavb \ @Eilon if we remove the warning for package must be listed in NuGetPackageVerifier.json, the default settings which are just as restrictive as `AdxVerificationCompositeRule` get used (and that's ok). Thoughts?

**Comment by ajaybhargavb** [comment]
I am okay with listing packages only if they need exceptions. But then we'll have to update all repos to have only the default package set. Otherwise, the packages list will just get outdated.

**Comment by Eilon** [comment]
Per a discussion from earlier today, there are a few things we need to clean up:

* Make NPV run on *every* dev build with all rules that will generally pass on local dev machines
* Remove the default list of packages; make sure that the default composite rule set that is used has the right rules
* Have the CI run all the rules that aren't runnable on dev builds

**Pull request closed without merging**
