### PR TITLE
Updating build script

### PR DESCRIPTION
**Pull request by natemcmaster**
react to https://github.com/aspnet/Universe/pull/351

### CODE REVIEW

**Comment by natemcmaster** [comment]
cc @victorhurdugaci I'll need to make this exact change to ~20 repos.

**Comment by pranavkm** [comment]
If you're simply copying things from the template, feel free to bulk update repos without sending PRs individually.

**Comment by pranavkm** [comment]
:shipit:

**Comment by victorhurdugaci** [comment]
No need for PR in each repo



On Thu, Jan 14, 2016 at 4:57 PM -0800, "Nate McMaster" <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #84<https://github.com/aspnet/Common/pull/84>.

-

**Pull request merged**
