### PR TITLE
Target minimal TFMs

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by Eilon** [comment]
:shipit: because I assume that as long as these compile, the TFMs don't matter at all.

**Comment by muratg** [comment]
Looks like you removed some of the imports. Will that work with CoreCLR packages that do not have netstandard?

**Comment by pranavkm** [comment]
@muratg - yeah all of those were shared src projects, so they weren't compiling to begin with. @davidfowl had a suggestion for us to create an additional project here that verified here if you could actually build it in the netstandard1.0 tfm. I'll work on that as part of this change.

**Comment by pranavkm** [comment]
I think we don't need the project I suggested in my earlier comment. This should be good as is.

**Comment by muratg** [comment]
:shipit:

**Pull request merged**
