### PR TITLE
Modify StringSegment.GetHashCode() to produce the same hash for equal…

### LINKED ISSUE #137: StringSegment GetHashCode() includes the Offset but Equals doesn't care about it
Surely `GetHashCode()` should not rely on the `Offset` since in `Equals`, two `StringSegments` are equal if they have equal values regardless as to where they are located in the string.

### PR DESCRIPTION
**Pull request by pranavkm**
… substrings.

Fixes #137

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @rynowak

**Comment by rynowak** [comment]
We discussed this in more detail and decided that we will need to substring inside `GetHashCode()` to do this correctly. We don't want to take on writing a correct hashcode for an arbitrary character sequence.

**Comment by pranavkm** [comment]
:up: :date:

**Comment by rynowak** [comment]
:shipit:

**Pull request merged**
