### PR TITLE
Move common command line code into CommandLineUtils

### LINKED ISSUE #173: Add more abstractions for console tools
We should consider reducing duplicate APIs into a common abstraction.

Examples:
Microsoft.Extensions.Tools.Internal.IConsole (aspnet/dotnettools)
MIcrosoft.Extensions.Logging.Console.Internal.IConsole (aspnet/logging)

Microsoft.DotNet.Cli.Utils.ArgumentEscaper (dotnet/cli)
Microsoft.Extensions.Tools.Internal.ArgumentEscaper (aspnet/dotnettools)
Microsoft.EntityFrameworkCore.Tools.VisualStudio.Internal.ArgumentEscaper (aspnet/entityframework.tools)

Microsoft.DotNet.Cli.Utils.Muxer (from dotnet/cli)
Microsoft.Extensions.Tools.Internal.DotNetMuxer (aspnet/dotnettools)
Internal.AspNetCore.BuildTools.Tasks.GetDotNetHost (aspnet/buildtools)

Some of this duplication was introduced to break a cyclical dependency between aspnet and CLI. https://github.com/dotnet/cli/issues/4745#issuecomment-261396513 

cc @piotrpMSFT @BrennanConroy

### PR DESCRIPTION
**Pull request by natemcmaster**
Remove duplication from our code. 

We have duplicate implementations of this code scattered around a few projects. By putting htis here, we can remove the duplicate code from aspnet/DotNetTools, aspnet/EntityFramework.Tools, aspnet/BuildTools, and maybe more.

Resolves #173

cc @Eilon @muratg  should we API review these before we add this?

### CODE REVIEW

**Comment by Eilon** [comment]
Can we chat for a few minutes about the various command line changes being proposed (not just this change)?

**Comment by natemcmaster** [comment]
:watch: until triage discussion next week.

**Comment by natemcmaster** [comment]
:up: :date: rebased on #205. Now that CommandLineUtils is a .Sources package only, we shouldn't have to worry as much about API review on this. This is just putting code in a common location that we already have duplicated in a few places.

**Comment by natemcmaster** [comment]
See also https://github.com/aspnet/DotNetTools/pull/280

**Comment by natemcmaster** [comment]
> I'm just wondering why some of the files moved into a CommandLineApplication

I don't remember what I was thinking. Updated with that change reverted.

**Comment by Eilon** [comment]
Re-approved 😄

**Pull request merged**
