### PR TITLE
Rename packages name from *.Internal to *.Sources

### PR DESCRIPTION
**Pull request by troydai**
Staging here, preparing reaction on dependents.

### CODE REVIEW

**Comment by dougbu** [comment]
@troydai why didn't you also rename the .xproj files and update the .sln that refers to them?  .sln is now broken in this repo.

**Comment by troydai** [comment]
@dougbu thanks for reminding! notepad is not enough ...

**Comment by troydai** [comment]
@dougbu updated!

**Comment by dougbu** [comment]
@troydai looks like you added most of the right changes to the repo in your additional commit.

The `test/Microsoft.Framework.Internal.Test/Microsoft.Framework.Internal.Test.xproj` directory / filename still sticks out like a sore thumb.  Shouldn't the name(s) be `Microsoft.Framework.Common.Test` or perhaps `Microsoft.Framework.Sources.Test`?

**Pull request merged**
