### PR TITLE
Use VSTS config from buildtools templates

### PR DESCRIPTION
**Pull request by natemcmaster**
cc @chcosta @ryanbrandenburg

### CODE REVIEW

**Comment by chcosta** [comment]
Is latest in the branch always going to be ok, or do you have a plan to version this?

**Comment by natemcmaster** [comment]
> Is latest in the branch always going to be ok, or do you have a plan to version this?

Yeah, that was one of my concerns too. We need to be really careful about this since its basically a 'floating' dependency. Do you have any ideas on how to reduce risk here?

My thinking is to keep branch names aligned. This repo (and almost all aspnet repos) have `dev`, `release/2.1`, `release/2.0` etc, and so does aspnet/BuildTools.

**Comment by chcosta** [comment]
I don't have any ideas at the moment (I haven't put any thought into it).  Aligning branch names may work in the short term but seems like such a weak dependency that it's likely to become problematic.  This is definitely something that deserves some thought as you're blazing the trail here.

**Comment by natemcmaster** [comment]
Yeah, let's think about this more as we move forward. I'm not too concerned about it because we have been able to use almost identical .appveyor.yml and .travis.yml files. As long as we preserve the template "API", I think we will be ok.

**Pull request merged**
