### PR TITLE
Clean up type name helper redux

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by smitpatel** [comment]
Looking at code, this would fail for `Level1<int>.Level2<int>.Level3<int>`

**Comment by smitpatel** [comment]
Multi-level indeed worked. Is there any benefit of using `ArraySegment<>` instead of doing allocations of that it would be better just to play around with indexers of the array.

**Comment by pranavkm** [comment]
`ArraySegment` is a value type.

**Comment by AndreyTretyak** [comment]
@pranavkm  This solution indeed looks much simpler, and I like usage of `ArraySegment` it makes code clearer. I think we don't need to worry about allocations of `ArraySegment` because it's a `struct`.

Should I update my PR to use logic that you proposed or I should just close it and you will accept this PR?

**Comment by pranavkm** [comment]
> Should I update my PR to use logic that you proposed or I should just close it and you will accept this PR?

Sure, that sounds good.

**Pull request closed without merging**
