### PR TITLE
Stop producing Microsoft.Extensions.CommandLineUtils

### PR DESCRIPTION
**Pull request by natemcmaster**
In our most recent triage meeting about this library, we decided to stop producing this library because we don't intend to make improvements and bug fixes unless we need them. This library was only intended for usage with ASP.NET Core's tools, and not a general purpose library.

We will still leave the 1.0.0 and 1.1.0 versions of this library on NuGet.org, but the current plan is to stop producing new versions of this package.

The source code is still available for internally in the Microsoft.Extensions.CommandLineUtils.Sources package.

cc @DamianEdwards

### CODE REVIEW

**Comment by muratg** [comment]
Once this is in, please make sure to update https://github.com/aspnet/Coherence/blob/dev/packages/packages.csv as well.

**Comment by natemcmaster** [comment]
This was the only usage of the library (as opposed to the .Sources version). https://github.com/aspnet/DotNetTools/pull/279

**Comment by natemcmaster** [comment]
@Eilon should we also move these types to the Microsoft.Extensions.Internal namespace?

**Comment by Eilon** [comment]
All the types are now `internal` already, no?

**Pull request merged**
