### PR TITLE
Target .NET Standard 2.0

### PR DESCRIPTION
**Pull request by natemcmaster**
Part of aspnet/Home#2045.

### CODE REVIEW

**Comment by natemcmaster** [comment]
:watch: https://github.com/aspnet/FileSystem/pull/276 and https://github.com/aspnet/DependencyInjection/pull/534

**Comment by pranavkm** [comment]
Can we remove the `#if` from https://github.com/aspnet/Common/blob/04e2b857352b74e3edad5f36abe1ec3abd114a08/shared/Microsoft.Extensions.CommandLineUtils.Sources/Utilities/DotNetMuxer.cs#L5? Looks :shipit: otherwise.

**Comment by natemcmaster** [comment]
The DotNetMuxer API is really only meant to be used on .NET Core. Maybe we should change the `#if` to be `#if NETCOREAPP2_0` instead.

**Comment by pranavkm** [comment]
> The DotNetMuxer API is really only meant to be used on .NET Core. Maybe we should change the #if to be #if NETCOREAPP2_0 instead.

Six of one half dozen of the other. Up to you though

**Pull request merged**
