### PR TITLE
T

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @benaadams

**Comment by benaadams** [comment]
[`TypeNameHelper.cs#L75`](https://github.com/aspnet/Common/blob/562d6bd490ae959e9da9c0c7e6f7656785595000/shared/Microsoft.Extensions.TypeNameHelper.Sources/TypeNameHelper.cs#L75) also needs to change to 
```
builder.Append(options.FullName ? type.FullName ?? type.Name : type.Name);
```

**Comment by pranavkm** [comment]
What scenarios is it null? We special case generic parameter names which was the one case I found it to be null  - https://github.com/aspnet/Common/blob/562d6bd490ae959e9da9c0c7e6f7656785595000/shared/Microsoft.Extensions.TypeNameHelper.Sources/TypeNameHelper.cs#L66-L72

**Comment by benaadams** [comment]
> What scenarios is it null?

Will get back to you... I have a suite of horrible functions (lambda/locals/ienumberables/generics/etc) and one of them triggered it - will see if your fix resolves it

**Comment by benaadams** [comment]
Can file and issue and do a PR if I find something that makes it necessary if you want to merge?

**Comment by pranavkm** [comment]
Sounds good. I'll get this merged in.

**Comment by pranavkm** [comment]
Thanks for the PR!

**Pull request merged**
